spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost/postgres
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: false
csvFilePath: file:///Users/rakeshsingh/workspace/proj/spring_batch_proj/spring-batch/spring-batch-ex/src/main/resources/books.csv